main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Index.as_view(),
         name='index'),
    path('kontakt/', views.Contact.as_view(),
         name='contact'),
    path('katalog/', views.Catalog.as_view(),
         name='catalog'),
    path('katalog/create-category', views.CreateProductCategory.as_view(),
         name='create-category'),
    path('katalog/<slug:category_slug>/', views.CategoryProducts.as_view(),
         name='category-details'),
    path('katalog/<slug:category_slug>/<slug:product_slug>/', views.ProductDetail.as_view(),
         name='product-details'),
    path('katalog/<slug:category_slug>/<slug:product_slug>/review/', views.CreateProductReview.as_view(),
         name='create-product-review'),
    path('katalog/<slug:category_slug>/create', views.CreateProduct.as_view(),
         name='create-product'),
    path('katalog/<slug:category_slug>/<slug:product_slug>/update/', views.UpdateProduct.as_view(),
         name='update-product'),
    path('katalog/<slug:category_slug>/<slug:product_slug>/delete/', views.DeleteProduct.as_view(),
         name='delete-product'),
]

remeslovkostce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
from django.utils import timezone


class ProductCategory(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)
    thumbnail = models.ImageField(upload_to='images', default='not-found.jpg')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:category-details', args=(self.slug,))


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.PROTECT)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='images/products', default='not-found.jpg')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product-details', args=(self.category.slug, self.slug))


class ProductReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    published = models.DateField(auto_now_add=True)
    rating = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    content = models.TextField()

    def __str__(self):
        return str(self.rating)

    def get_absolute_url(self):
        return f'{self.product.get_absolute_url()}#{self.pk}'

main/forms.py
from django import forms

from . import models


class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = models.ProductReview
        fields = "__all__"
        widgets = {
            'product': forms.HiddenInput,
            'rating': forms.NumberInput(
                attrs={'class': 'form-control', 'placeholder': 'Hodnocení produktu', 'min': 0, 'max': 100, 'value': 0}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Obsah recenze'})
        }
        labels = {
            'rating': 'Hodnocení produktu',
            'content': 'Obsah recenze'
        }
        help_texts = {
            'rating': 'Hodnocení od 1% do 100%'
        }
        error_messages = {
            'rating': {
                'min_value': 'Hodnocení produktu musí být mezi 1%% - 100%%',
                'max_value': 'Hodnocení produktu musí být mezi 1%% - 100%%'
            },
            'content': {
                'required': 'Obsah recenze nesmí být prázdný'
            }
        }


class UpdateProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = ['category', 'name', 'slug', 'description', 'image']
        widgets = {
            'category': forms.Select(attrs={'class': 'form-select'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Název produktu'}),
            'slug': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Slug produktu'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Popis produktu'}),
        }
        labels = {
            'category': 'Kategorie',
            'name': 'Název produktu',
            'description': 'Popis produktu',
            'image': 'Foto produktu'
        }


class CreateProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = ['category', 'name', 'slug', 'description', 'image']
        widgets = {
            'category': forms.HiddenInput(),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Název produktu'}),
            'slug': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Slug produktu'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Popis produktu'}),
        }
        labels = {
            'category': 'Kategorie',
            'name': 'Název produktu',
            'description': 'Popis produktu',
            'image': 'Foto produktu'
        }


class CreateProductCategoryForm(forms.ModelForm):
    class Meta:
        model = models.ProductCategory
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }
        labels = {
            'name': 'Jméno kategorie',
            'description': 'Popis kategorie',
            'thumbnail': 'Náhledový obrázek'
        }

main/views.py
from django.shortcuts import get_object_or_404
from django.views import generic

from .models import *
from . import forms


# Create your views here.

class Index(generic.TemplateView):
    template_name = 'index.html'
    extra_context = {'index': True}


class Contact(generic.TemplateView):
    template_name = 'contact.html'
    extra_context = {'contact': True}


class Catalog(generic.ListView):
    model = ProductCategory
    template_name = 'catalog.html'
    context_object_name = 'categories'
    extra_context = {'catalog': True}


class CategoryProducts(generic.ListView):
    template_name = 'category.html'
    context_object_name = 'products'
    extra_context = {'catalog': True}

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['category_slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['category'] = ProductCategory.objects.get(slug=self.kwargs['category_slug'])
        except ProductCategory.DoesNotExist:
            context['error_message'] = 'Tato kategorie produktů neexistuje'
        return context


class ProductDetail(generic.DetailView):
    model = Product
    template_name = 'product-details.html'
    context_object_name = 'product'
    slug_url_kwarg = 'product_slug'
    extra_context = {'catalog': True}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviews'] = ProductReview.objects.filter(product_id=self.object.pk)
        return context


class CreateProduct(generic.CreateView):
    model = Product
    form_class = forms.CreateProductForm
    template_name = 'create-product.html'

    extra_context = {'catalog': True}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        try:
            context['category'] = ProductCategory.objects.get(slug=self.kwargs['category_slug'])
        except ProductCategory.DoesNotExist:
            context['error_message'] = 'Tato kategorie produktů neexistuje'
        return context

    def get_initial(self):
        initial = super().get_initial()

        try:
            initial['category'] = ProductCategory.objects.get(slug=self.kwargs['category_slug'])
        except ProductCategory.DoesNotExist:
            pass
        return initial


class UpdateProduct(generic.UpdateView):
    model = Product
    form_class = forms.UpdateProductForm
    template_name = 'update-product.html'
    slug_url_kwarg = 'product_slug'

    extra_context = {'catalog': True}


class DeleteProduct(generic.DeleteView):
    model = Product
    template_name = 'delete-product.html'
    slug_url_kwarg = 'product_slug'

    extra_context = {'catalog': True}

    def get_success_url(self):
        return self.object.category.get_absolute_url()


class CreateProductCategory(generic.CreateView):
    model = ProductCategory
    form_class = forms.CreateProductCategoryForm
    template_name = 'create-product-category.html'

    extra_context = {'catalog': True}


class CreateProductReview(generic.CreateView):
    model = ProductReview
    form_class = forms.ProductReviewForm
    template_name = 'create-product-review.html'

    extra_context = {'catalog': True}

    product = None

    def load_data(self):
        if self.product is None:
            self.product = get_object_or_404(Product, slug=self.kwargs['product_slug'])

    def get_context_data(self, **kwargs):
        self.load_data()
        context = super().get_context_data(**kwargs)
        context['product'] = self.product
        return context

    def get_initial(self):
        self.load_data()
        initial = super().get_initial()
        initial['product'] = self.product.pk
        return initial

main/templates/partials/category-card.html
<div class="col-lg-4 mb-3">
    <div class="card h-100">
        <div class="card-body">
            <div class="row">
                <div class="col-12 text-center">
                    <h4 class="card-title">{{ category.name }}</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <img class="img-thumbnail"
                         src="{{ category.thumbnail.url }}"
                         alt="{{ category.slug }}">
                </div>
                <div class="col-6">
                    <p class="card-text">{{ category.description }}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-12 text-center">
                    <a href="{{ category.get_absolute_url }}" class="btn btn-primary mt-3">
                        Přejít k produktům
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

main/templates/partials/category_card.html
<div class="col-lg-4 mb-3">
    <div class="card h-100">
        <div class="card-body">
            <div class="row">
                <div class="col-12 text-center">
                    <h4 class="card-title">{{ category.name }}</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <img class="img-thumbnail"
                         src="{{ category.thumbnail.url }}"
                         alt="{{ category.slug }}">
                </div>
                <div class="col-6">
                    <p class="card-text">{{ category.description }}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-12 text-center">
                    <a href="{{ category.get_absolute_url }}" class="btn btn-primary mt-3">
                        Přejít k produktům
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

main/templates/partials/footer.html
{% load tags %}
<footer class="text-light bg-dark w-100 fixed-bottom" style="opacity: 0.9">
    <div class="text-center">
        Řemeslo v kostce &COPY; {% current_year %}<br><span class="text-muted font-weight-light">by Petr Boháč</span>
    </div>
</footer>

main/templates/partials/navigation.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark w-100">
    <div class="container">
        <a class="navbar-brand"
           href="/">Řemeslo v kostce</a>
        <button class="navbar-toggler" type="button"
                data-toggle="collapse"
                data-target="#navbarResponsive"
                aria-controls="navbarResponsive"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto pl-4">
                <li class="nav-item">
                    <a href="{% url 'main:index' %}" class="nav-link {% if index %}active{% endif %}">Domů</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'main:catalog' %}" class="nav-link {% if catalog %}active{% endif %}">Katalog</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'main:contact' %}" class="nav-link {% if contact %}active{% endif %}">Kontakty</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

main/templates/partials/product-card.html
{% load custom_filters %}
<div class="col-lg-4 mb-3">
    <div class="card h-100">
        <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.slug }}">
        <div class="card-body d-flex flex-column">
            <h4 class="card-title">{{ product.name }}</h4>
            <p class="card-text">{{ product | description:75 }}</p>
            <a href="{{ product.get_absolute_url }}" class="btn btn-primary stretched-link align-self-start mt-auto">
                Detail produktu
            </a>
        </div>
    </div>
</div>

main/templates/partials/review-card.html
<div class="card mb-3" id="{{ review.pk }}">
    <div class="card-body">
        <div class="row">
            <div class="col-md-2">
                <img src="https://image.ibb.co/jw55Ex/def_face.jpg"
                     class="img img-rounded img-fluid"/>
                <p class="text-secondary text-center">{{ review.published }}</p>
            </div>
            <div class="col-md-10">
                <div class="row">
                    <div class="col-3">
                        <p><strong>Anonymní uživatel</strong></p>
                    </div>
                    <div class="col-9">
                        <div class="progress">
                            <div class="progress-bar bg-warning" role="progressbar" style="width: {{ review.rating }}%;"
                                 aria-valuenow="{{ review.rating }}"
                                 aria-valuemin="0" aria-valuemax="100">{{ review.rating }}%
                            </div>
                        </div>
                    </div>
                </div>
                <p>{{ review.content }}</p>
            </div>
        </div>
    </div>
</div>