main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Index.as_view(),
         name='index'),
    path('kontakt/', views.Contact.as_view(),
         name='contact'),
    path('katalog/', views.Catalog.as_view(),
         name='catalog'),
    path('katalog/create-category', views.CreateProductCategory.as_view(),
         name='create-category'),
    path('katalog/<slug:category_slug>/', views.CategoryProducts.as_view(),
         name='category-details'),
    path('katalog/<slug:category_slug>/<slug:product_slug>/', views.ProductDetail.as_view(),
         name='product-details'),
    path('katalog/<slug:category_slug>/<slug:product_slug>/review/', views.CreateProductReview.as_view(),
         name='create-product-review'),
    path('katalog/<slug:category_slug>/create', views.CreateProduct.as_view(),
         name='create-product'),
    path('katalog/<slug:category_slug>/<slug:product_slug>/update/', views.UpdateProduct.as_view(),
         name='update-product'),
    path('katalog/<slug:category_slug>/<slug:product_slug>/delete/', views.DeleteProduct.as_view(),
         name='delete-product'),
]

remeslovkostce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
from django.utils import timezone


class ProductCategory(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)
    thumbnail = models.ImageField(upload_to='images', default='not-found.jpg')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:category-details', args=(self.slug,))


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.PROTECT)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='images/products', default='not-found.jpg')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product-details', args=(self.category.slug, self.slug))


class ProductReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    published = models.DateField(auto_now_add=True)
    rating = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    content = models.TextField()

    def __str__(self):
        return str(self.rating)

    def get_absolute_url(self):
        return f'{self.product.get_absolute_url()}#{self.pk}'

main/forms.py
from django import forms

from . import models


class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = models.ProductReview
        fields = "__all__"
        widgets = {
            'product': forms.HiddenInput,
            'rating': forms.NumberInput(
                attrs={'class': 'form-control', 'placeholder': 'Hodnocení produktu', 'min': 0, 'max': 100, 'value': 0}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Obsah recenze'})
        }
        labels = {
            'rating': 'Hodnocení produktu',
            'content': 'Obsah recenze'
        }
        help_texts = {
            'rating': 'Hodnocení od 1% do 100%'
        }
        error_messages = {
            'rating': {
                'min_value': 'Hodnocení produktu musí být mezi 1%% - 100%%',
                'max_value': 'Hodnocení produktu musí být mezi 1%% - 100%%'
            },
            'content': {
                'required': 'Obsah recenze nesmí být prázdný'
            }
        }


class UpdateProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = ['category', 'name', 'slug', 'description', 'image']
        widgets = {
            'category': forms.Select(attrs={'class': 'form-select'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Název produktu'}),
            'slug': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Slug produktu'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Popis produktu'}),
        }
        labels = {
            'category': 'Kategorie',
            'name': 'Název produktu',
            'description': 'Popis produktu',
            'image': 'Foto produktu'
        }


class CreateProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = ['category', 'name', 'slug', 'description', 'image']
        widgets = {
            'category': forms.HiddenInput(),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Název produktu'}),
            'slug': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Slug produktu'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Popis produktu'}),
        }
        labels = {
            'category': 'Kategorie',
            'name': 'Název produktu',
            'description': 'Popis produktu',
            'image': 'Foto produktu'
        }


class CreateProductCategoryForm(forms.ModelForm):
    class Meta:
        model = models.ProductCategory
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }
        labels = {
            'name': 'Jméno kategorie',
            'description': 'Popis kategorie',
            'thumbnail': 'Náhledový obrázek'
        }

main/views.py
from django.shortcuts import get_object_or_404
from django.views import generic

from .models import *
from . import forms


# Create your views here.

class Index(generic.TemplateView):
    template_name = 'index.html'
    extra_context = {'index': True}


class Contact(generic.TemplateView):
    template_name = 'contact.html'
    extra_context = {'contact': True}


class Catalog(generic.ListView):
    model = ProductCategory
    template_name = 'catalog.html'
    context_object_name = 'categories'
    extra_context = {'catalog': True}


class CategoryProducts(generic.ListView):
    template_name = 'category.html'
    context_object_name = 'products'
    extra_context = {'catalog': True}

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['category_slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['category'] = ProductCategory.objects.get(slug=self.kwargs['category_slug'])
        except ProductCategory.DoesNotExist:
            context['error_message'] = 'Tato kategorie produktů neexistuje'
        return context


class ProductDetail(generic.DetailView):
    model = Product
    template_name = 'product-details.html'
    context_object_name = 'product'
    slug_url_kwarg = 'product_slug'
    extra_context = {'catalog': True}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviews'] = ProductReview.objects.filter(product_id=self.object.pk)
        return context


class CreateProduct(generic.CreateView):
    model = Product
    form_class = forms.CreateProductForm
    template_name = 'create-product.html'

    extra_context = {'catalog': True}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        try:
            context['category'] = ProductCategory.objects.get(slug=self.kwargs['category_slug'])
        except ProductCategory.DoesNotExist:
            context['error_message'] = 'Tato kategorie produktů neexistuje'
        return context

    def get_initial(self):
        initial = super().get_initial()

        try:
            initial['category'] = ProductCategory.objects.get(slug=self.kwargs['category_slug'])
        except ProductCategory.DoesNotExist:
            pass
        return initial


class UpdateProduct(generic.UpdateView):
    model = Product
    form_class = forms.UpdateProductForm
    template_name = 'update-product.html'
    slug_url_kwarg = 'product_slug'

    extra_context = {'catalog': True}


class DeleteProduct(generic.DeleteView):
    model = Product
    template_name = 'delete-product.html'
    slug_url_kwarg = 'product_slug'

    extra_context = {'catalog': True}

    def get_success_url(self):
        return self.object.category.get_absolute_url()


class CreateProductCategory(generic.CreateView):
    model = ProductCategory
    form_class = forms.CreateProductCategoryForm
    template_name = 'create-product-category.html'

    extra_context = {'catalog': True}


class CreateProductReview(generic.CreateView):
    model = ProductReview
    form_class = forms.ProductReviewForm
    template_name = 'create-product-review.html'

    extra_context = {'catalog': True}

    product = None

    def load_data(self):
        if self.product is None:
            self.product = get_object_or_404(Product, slug=self.kwargs['product_slug'])

    def get_context_data(self, **kwargs):
        self.load_data()
        context = super().get_context_data(**kwargs)
        context['product'] = self.product
        return context

    def get_initial(self):
        self.load_data()
        initial = super().get_initial()
        initial['product'] = self.product.pk
        return initial

main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'fontawesomefree/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesomefree/js/all.min.js' %}">
    <title>{% block title %}{% endblock %} | Řemeslo v kostce</title>
</head>
<body>
{% include 'partials/navigation.html' %}
<div class="container-fluid">
    {% block body %}{% endblock %}
</div>
{% include 'partials/footer.html' %}
</body>
</html>

main/templates/catalog.html
{% extends 'base.html' %}
{% block title %}Katalog{% endblock %}
{% block body %}
    <div class="row my-5">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <div class="d-flex justify-content-between">
                <h4>Katalog</h4>
                {% if user.is_authenticated %}
                    <a href="{% url 'main:create-category' %}" class="btn btn-success">Přidat kategorii</a>
                {% endif %}
            </div>
            <hr>
            <div class="row">
                {% for category in categories %}
                    {% include 'partials/category-card.html' %}
                {% endfor %}
            </div>
        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}

main/templates/category.html
{% extends 'base.html' %}
{% block title %}
    {% if error_message %}
        Někde se vyskytla chyba
    {% else %}
        {{ category }}
    {% endif %}
{% endblock %}
{% block body %}
    <div class="row my-5">
        <div class="col-lg-2">
            <a href="{% url 'main:catalog' %}" class="btn btn-outline-info float-end mb-2">
                Zpět na Katalog
            </a>
        </div>
        <div class="col-lg-8">
            {% if error_message %}
                <div class="alert alert-danger text-center mt-3" role="alert">
                    {{ error_message }}
                </div>
            {% else %}
                <div class="d-flex justify-content-between">
                    <h4>{{ category }}</h4>
                    {% if user.is_authenticated %}
                        <a href="{% url 'main:create-product' category.slug %}" class="btn btn-success">
                            Přidat produkt
                        </a>
                    {% endif %}
                </div>
                <hr>
                {% if products.count == 0 %}
                    <div class="alert alert-warning text-center" role="alert">
                        Tato kategoriie neobsahuje žádné produkty
                    </div>
                {% endif %}
                <div class="row">
                    {% for product in products %}
                        {% include 'partials/product-card.html' %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}

main/templates/contact.html
{% extends 'base.html' %}
{% block title %}Kontakt{% endblock %}
{% block body %}
    <div class="row my-5">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <h4>Kontakt</h4>
            <hr>
            <div class="card mb-3">
                <div class="card-header"><h5>Petr Boháč</h5></div>
                <div class="card-body">
                    <ul class="list-unlisted p-0"><b>Pozice:</b><br>Majitel a Zakladatel</ul>
                    <ul class="list-unlisted p-0"><b>Adresa:</b><br>Jatecká 399<br>Mšeno<br>277 35<br>Česká Republika
                    </ul>
                    <ul class="list-unlisted p-0"><b>Kontakt:</b><br><b>Telefon</b><br>+420 315 693 889<b><br>E-mail</b><br><a
                            href="mailto:obchod@remeslovkostce.cz">obchod@remeslovkostce.cz</a></ul>
                    <ul class="list-unlisted p-0"><b>Ostatní informace:</b><br><b>IČ</b><br>10161171<br><b>DIČ</b><br>CZ6703151488
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}

main/templates/create-product-category.html
{% extends 'base.html' %}
{% block title %}Přidat kategorii{% endblock %}
{% block body %}
    <div class="row my-5">
        <div class="col-lg-2">
            <a href="{% url 'main:catalog' %}" class="btn btn-outline-info float-end mb-2">
                Zpět na Katalog
            </a>
        </div>
        <div class="col-lg-8">
            <h4>Přidat novou kategorii</h4>
            <hr>
            <form method="post">
                <div class="form-group">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-outline-primary" value="Odeslat">
                </div>
            </form>
        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}

main/templates/create-product-review.html
{% extends 'base.html' %}
{% block title %}Přidat recenzi{% endblock %}
{% block body %}
    <div class="row mt-5">
        <div class="col-lg-2">
            <a href="{{ product.get_absolute_url }}" class="btn btn-outline-info float-end">Zpět na detail produktu</a>
        </div>
        <div class="col-lg-8">
            <h4>Přidat recenzi k produktu {{ product }}</h4>
            <hr>
            <form method="post">
                <div class="form-group">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-outline-primary" value="Odeslat">
                </div>
            </form>
        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}

main/templates/create-product.html
{% extends 'base.html' %}
{% block title %}Přidat produkt{% endblock %}
{% block body %}
    <div class="row my-5">
        <div class="col-lg-2">
            {% if not error_message %}
                <a href="{{ category.get_absolute_url }}" class="btn btn-outline-info float-end mb-2">
                    Zpět na detail produktu
                </a>
            {% endif %}
        </div>
        <div class="col-lg-8">
            {% if not error_message %}
                <h4>Přidat produkt do kategorie {{ category }}</h4>
                <hr>
                <form method="post">
                    <div class="form-group">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" class="btn btn-outline-primary" value="Odeslat">
                    </div>
                </form>
            {% else %}
                <div class="alert alert-danger text-center mt-3" role="alert">
                    {{ error_message }}
                </div>
            {% endif %}
        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}

main/templates/create_product_review.html
{% extends 'base.html' %}
{% block title %}Přidat recenzi{% endblock %}
{% block body %}
    <div class="row mt-5">
        <div class="col-lg-2">
            <a href="{{ product.get_absolute_url }}" class="btn btn-outline-info float-end">Zpět na detail produktu</a>
        </div>
        <div class="col-lg-8">
            <h4>Přidat recenzi k produktu {{ product }}</h4>
            <hr>
            <form method="post">
                <div class="form-group">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-outline-primary" value="Odeslat">
                </div>
            </form>
        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}

main/templates/delete-product.html
{% extends 'base.html' %}
{% block title %}Odstranit produkt{% endblock %}
{% block body %}
    <div class="row my-5    ">
        <div class="col-lg-2">
            <a href="{{ product.get_absolute_url }}" class="btn btn-outline-info float-end">
                Zpět na detail produktu
            </a>
        </div>
        <div class="col-lg-8">
            <h5>Opravdu chcete odstranit produkt {{ product }}?</h5>
            <hr>
            <form method="post">
                {% csrf_token %}
                <label for="slug-input">Pro potvrzení prosím napište <b>{{ product.slug }}</b>.</label>
                <div class="input-group mt-2">
                    <input id="slug-input" type="text" class="form-control" placeholder="Slug produktu">
                    <div class="input-group-append">
                        <input id="delete-button" type="submit" class="btn btn-danger" value="Odstranit" disabled>
                    </div>
                </div>
            </form>
            <script>
                slug_input = document.getElementById('slug-input')
                delete_button = document.getElementById('delete-button')
                slug_input.addEventListener('input', () => delete_button.disabled = slug_input.value !== '{{ product.slug}}')
            </script>
        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}

main/templates/error.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Vyskytla se chyba{% endblock %}
{% block body %}
    <div class="row mt-5">
        <div class="col-lg-2"></div>
        <div class="col-lg-8 text-center my-5">
            <h3>{{ message }}</h3>
            <hr>
            <img src="{% static 'error.png' %}" alt="error icon">
        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}

main/templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block body %}
    <div class="row my-5">
        <div class="col-lg-2"></div>
        <div class="col-lg-8 text-center">
            <h4>Vítejte na stránkách Řemeslo v kostce</h4>
            <hr>
            <p><b>ŘEMESLO V KOSTCE</b> je ryze výrobní firma zaměřená především
                na
                zpracování papíru. Kancelářské potřeby a reklamní předměty
                spotřebního charakteru vyrábíme od roku 1997. </p>
            <p>Naše zboží lze zakoupit v celé řadě obchodů po celé ČR. Pokud
                máte
                zájem o velkoobchodní podmínky prodeje, prosím kontaktujte nás
                na
                <a href="mailto:obchod@remeslovkostce.cz">obchod@remeslovkostce.cz</a>.
            </p>
            <p>Přehled našich výrobků naleznete v sekci <a
                    href="{% url 'main:catalog' %}">Katalog</a>.</p>

        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}

main/templates/product-details.html
{% extends 'base.html' %}
{% block title %}
    {% if error_message %}
        Někde se vyskytla chyba
    {% else %}
        {{ product.name }}
    {% endif %}
{% endblock %}
{% block body %}
    <div class="row my-5">
        <div class="col-lg-2">
            <a href="{{ product.category.get_absolute_url }}" class="btn btn-outline-info float-end mb-2">
                Zpět na {{ product.category }}
            </a>
        </div>
        <div class="col-lg-8">
            {% if not error_message %}
                <div class="d-flex justify-content-between">
                    <h4>{{ product }}</h4>
                    {% if user.is_authenticated %}
                        <div>
                            <a href="{% url 'main:update-product' product.category.slug product.slug %}"
                               class="btn btn-warning">Upravit</a>
                            <a href="{% url 'main:delete-product' product.category.slug product.slug %}"
                               class="btn btn-danger">Odstranit</a>
                        </div>
                    {% endif %}
                </div>
                <hr>
                <div class="row">
                    {% if not error_message %}
                        <div class="row">
                            <div class="col-6">
                                <a href="{{ product.image.url }}" target="_blank">
                                    <img src="{{ product.image.url }}" alt="{{ product.slug }}" class="img-fluid">
                                </a>
                            </div>
                            <div class="col-6">
                                <h5>Popis produktu</h5>
                                <hr>
                                {% if not product.description %}
                                    <div class="alert alert-info text-center" role="alert">
                                        Popis produktu není dostupný
                                    </div>
                                {% endif %}
                                <div class="mb-4">{{ product.description }}</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 mt-4">
                                <div class="d-flex justify-content-between">
                                    <h5>Recenze <span class="text-muted">({{ reviews.count }})</span></h5>
                                    <a href="{% url 'main:create-product-review' product.category.slug product.slug %}"
                                       class="float-end btn btn-outline-primary">Přidat recenzi</a>
                                </div>
                                <hr>
                                {% if not reviews %}
                                    <div class="alert alert-primary text-center" role="alert">
                                        Nikdo dosud nezanechal recenzi k tomuto produktu, <a
                                            href="{% url 'main:create-product-review' product.category.slug product.slug %}">buďte
                                        první</a>.
                                    </div>
                                {% endif %}
                                {% for review in reviews %}
                                    {% include 'partials/review-card.html' %}
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
                </div>
            {% else %}
                <div class="alert alert-danger text-center mt-3" role="alert">
                    {{ error_message }}
                </div>
            {% endif %}
        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}

main/templates/product_details.html
{% extends 'base.html' %}
{% block title %}
    {% if error_message %}
        Někde se vyskytla chyba
    {% else %}
        {{ product.name }}
    {% endif %}
{% endblock %}
{% block body %}
    <div class="row mt-5">
        <div class="col-lg-2">
            <a href="{{ product.category.get_absolute_url }}" class="btn btn-outline-info float-end">Zpět
                na {{ product.category }}</a>
        </div>
        <div class="col-lg-8">
            {% if not error_message %}
                <h4>{{ product.name }}</h4>
                <hr>
                <div class="row mb-5">
                    {% if not error_message %}
                        <div class="row">
                            <div class="col-6">
                                <a href="{{ product.image.url }}" target="_blank">
                                    <img src="{{ product.image.url }}" alt="{{ product.slug }}" class="img-fluid">
                                </a>
                            </div>
                            <div class="col-6">
                                <h5>Popis produktu</h5>
                                <hr>
                                {% if not product.description %}
                                    <div class="alert alert-info text-center" role="alert">
                                        Popis produktu není dostupný
                                    </div>
                                {% endif %}
                                <div class="mb-4">{{ product.description }}</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 mt-4">
                                <div class="d-flex justify-content-between">
                                    <h5>Recenze <span class="text-muted">({{ reviews.count }})</span></h5>
                                    <a href="{% url 'main:product_details' product.category.slug product.slug %}review"
                                       class="float-end btn btn-outline-primary">Přidat recenzi</a>
                                </div>
                                <hr>
                                {% if not reviews %}
                                    <div class="alert alert-primary text-center" role="alert">
                                        Nikdo dosud nezanechal recenzi k tomuto produktu, <a
                                            href="{% url 'main:create_product_review' product.category.slug product.slug %}">buďte
                                        první</a>.
                                    </div>
                                {% endif %}
                                {% for review in reviews %}
                                    {% include 'partials/review-card.html' %}
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
                </div>
            {% else %}
                <div class="alert alert-danger text-center mt-3" role="alert">
                    {{ error_message }}
                </div>
            {% endif %}
        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}

main/templates/update-product.html
{% extends 'base.html' %}
{% block title %}Upravit produkt{% endblock %}
{% block body %}
    <div class="row mt-5">
        <div class="col-lg-2">
            <a href="{{ product.get_absolute_url }}" class="btn btn-outline-info float-end">Zpět na detail produktu</a>
        </div>
        <div class="col-lg-8">
            <h4>Upravit produkt {{ product }}</h4>
            <hr>
            {% comment %}Need to style the image selector input, also add the autofill for slug field depending on the product name field{% endcomment %}
            <form method="post">
                <div class="form-group">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-outline-primary" value="Odeslat">
                </div>
            </form>
        </div>
        <div class="col-lg-2"></div>
    </div>
{% endblock %}